// Test generated by RoostGPT for test httpfileserver-test using AI Type Open AI and AI Model gpt-4

package httpfileserver_test

import (
	"testing"
)

type fileServer struct {
	optionMaxBytesPerFile int
}

type Option func(*fileServer)

func OptionMaxBytes(optionMaxBytesPerFile int) Option {
	return func(fs *fileServer) {
		fs.optionMaxBytesPerFile = optionMaxBytesPerFile
	}
}

func TestOptionMaxBytes_1b8c6fdb68(t *testing.T) {
	tt := []struct {
		name     string
		input    int
		expected int
	}{
		{
			name:     "Test with positive number",
			input:    1024,
			expected: 1024,
		},
		{
			name:     "Test with zero",
			input:    0,
			expected: 0,
		},
		{
			name:     "Test with negative number",
			input:    -1024,
			expected: -1024,
		},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			fs := &fileServer{}
			opt := OptionMaxBytes(tc.input)
			opt(fs)
			if fs.optionMaxBytesPerFile != tc.expected {
				t.Errorf("Expected %d, but got %d", tc.expected, fs.optionMaxBytesPerFile)
			}
		})
	}
}
